export const themes = [
  {
    id: 'elegant-wedding',
    nameEs: 'Boda Elegante',
    nameEn: 'Elegant Wedding',
    emoji: '💍',
    bannerEs: '¡Listos para la Luna de Miel! 🥂',
    bannerEn: "We're Ready for the Honeymoon! 🥂",
  },
  {
    id: 'corporate-glow',
    nameEs: 'Brillo Corporativo',
    nameEn: 'Corporate Glow',
    emoji: '🏙️',
    bannerEs: '¡Empleado del Mes! ⭐',
    bannerEn: 'Employee of the Month! ⭐',
  },
  {
    id: 'xv-anos-royalty',
    nameEs: 'Realeza de XV Años',
    nameEn: 'XV Años Royalty',
    emoji: '👑',
    bannerEs: '¡Felices 15 Años, Princesa! 👑',
    bannerEn: 'Happy 15th Birthday, Princess! 👑',
  },
  {
    id: 'tropical-fiesta',
    nameEs: 'Fiesta Tropical',
    nameEn: 'Tropical Fiesta',
    emoji: '🌺',
    bannerEs: '¡Que Viva la Fiesta! 🌴',
    bannerEn: 'Que Viva la Fiesta! 🌴',
  },
  {
    id: 'futuristic-neon',
    nameEs: 'Neón Futurista',
    nameEn: 'Futuristic Neon',
    emoji: '🌆',
    bannerEs: '¡Bienvenido al Futuro! ⚡',
    bannerEn: 'Welcome to the Future! ⚡',
  },
  {
    id: 'birthday-bash',
    nameEs: 'Fiesta de Cumpleaños',
    nameEn: 'Birthday Bash',
    emoji: '🎂',
    bannerEs: '¡Feliz Cumpleaños! 🎂',
    bannerEn: 'Happy Birthday! 🎂',
  },
  {
    id: 'holiday-magic',
    nameEs: 'Magia Navideña',
    nameEn: 'Holiday Magic',
    emoji: '🎄',
    bannerEs: '¡Feliz Navidad! 🎄',
    bannerEn: 'Happy Holidays! 🎄',
  },
]
